%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\arvr19\Desktop\VR\VRslowCapture.txt
%
% Auto-generated by MATLAB on 30-Jul-2019 13:54:38

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["Var1", "Var2", "Var3", "Var4", "Var5", "VarName6", "VarName7", "VarName8", "VarName9"];
opts.SelectedVariableNames = ["VarName6", "VarName7", "VarName8", "VarName9"];
opts.VariableTypes = ["string", "string", "string", "string", "string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5, 6, 7, 8, 9], "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
VRslowCapture1 = readtable("C:\Users\arvr19\Desktop\VR\VRRoll1000.txt", opts);

%% Convert to output type
VRslowCapture1 = table2array(VRslowCapture1);

for k1 = 1:length(VRslowCapture1)   
    for k2 = 1:4
        quat{k1,k2} = VRslowCapture1{k1,k2};
        fprintf('%d = %s\n', k2, quat{k1,k2});
        iscell(quat);
    end
     Renew = quat(~cellfun(@isempty,quat));
     vector = str2double(Renew);
     if k1 >= 2
         vector = vector';
     end
     quater = quaternion(vector);
     eulerAnglesDegrees{k1} = eulerd(quater,'XYZ','frame');
     Degree = cell2mat(eulerAnglesDegrees');
     filename = 'testQuat.xlsx';
     writematrix(Degree,filename,'Sheet',1,'Range','D1');
     for k2 = 1:4
        quat{k1,k2} = {};
    end    
end

%% Clear temporary variables
clear opts