%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\arvr19\Desktop\VRslowCapture.xlsx
%    Worksheet: VRslowCapture
%
% Auto-generated by MATLAB on 01-Aug-2019 09:45:08

%% Setup the Import Options
clearvars
close all
opts = spreadsheetImportOptions("NumVariables", 1);

% Specify sheet and range
opts.Sheet = "VRslowCapture";
opts.DataRange = "L1:L5552";

% Specify column names and types
opts.VariableNames = "Duration";
opts.SelectedVariableNames = "Duration";
opts.VariableTypes = "double";

% Import the data
VRslowCaptureS1 = readtable("C:\Users\arvr19\Desktop\VRslowCapture.xlsx", opts, "UseExcel", false);

%SensorSlowCaptureS1 = readtable("C:\Users\arvr19\Desktop\SensorSlowCapture.xlsx", opts, "UseExcel", false);

% Read VR Excel data 
duration = xlsread('C:\Users\arvr19\Desktop\VRslowCapture.xlsx', 'VRslowCapture', 'L1:L5552');

yaw = xlsread('C:\Users\arvr19\Desktop\VRslowCapture.xlsx', 'VRslowCapture', 'N1:N5552');
pitch = xlsread('C:\Users\arvr19\Desktop\VRslowCapture.xlsx', 'VRslowCapture', 'O1:O5552');
roll = xlsread('C:\Users\arvr19\Desktop\VRslowCapture.xlsx', 'VRslowCapture', 'P1:P5552');
yaw=unwrap(yaw/180*pi)/pi*180;

roll=unwrap(roll/180*pi)/pi*180;


figure,
 p = plot(duration, yaw,'r.');
 hold on
 plot(duration, pitch,'g.')
 plot(duration, roll,'b.');
 legend('y','p','r')
 xlabel('duration');
 ylabel('VRrotation');
 %resampleVRyaw = resample(yaw,3,2);
 %resampleVRpitch = resample(pitch,3,2);
 %resampleVRroll = resample(roll,3,2);
 %resampleVRplot = plot(duration,resampleVRyaw,duration,resampleVRpitch,duration,resampleVRroll);
 
 % Read Sensor Excel data
 
 duration1 = xlsread('C:\Users\arvr19\Desktop\SensorSlowCapture.xlsx', 'SensorSlowCapture', 'L1:L584');
 
yaw1 = xlsread('C:\Users\arvr19\Desktop\SensorSlowCapture.xlsx', 'SensorSlowCapture', 'E1:E5552');
pitch1 = xlsread('C:\Users\arvr19\Desktop\SensorSlowCapture.xlsx', 'SensorSlowCapture', 'F1:F5552');
roll1 = xlsread('C:\Users\arvr19\Desktop\SensorSlowCapture.xlsx', 'SensorSlowCapture', 'G1:G5552');
 yaw1=unwrap(yaw1/180*pi)/pi*180;

roll1=unwrap(roll1/180*pi)/pi*180;
figure,
 p = plot(duration1, yaw1,'r.');
 hold on
 plot(duration1, pitch1,'g.')
 plot(duration1, roll1,'b.');
 legend('y','p','r')
% p1 = plot(duration1, yaw1, duration1, pitch1, duration1, roll1);
xlabel('duration');
ylabel('SensorRotation');

% Read resampledVR data 
durationResampled = xlsread('C:\Users\arvr19\Desktop\VR\ResampledMergedSensorVR.xlsx', 'Sheet1', 'G2:G4055');

yawResampled = xlsread('C:\Users\arvr19\Desktop\VR\ResampledMergedSensorVR.xlsx', 'Sheet1', 'H2:H4055');
pitchResampled = xlsread('C:\Users\arvr19\Desktop\VR\ResampledMergedSensorVR.xlsx', 'Sheet1', 'I2:I4055');
rollResampled = xlsread('C:\Users\arvr19\Desktop\VR\ResampledMergedSensorVR.xlsx', 'Sheet1', 'J2:J4055');

%  p2 = plot(durationResampled, yawResampled, durationResampled, pitchResampled, durationResampled, rollResampled);
%% Clear temporary variables
clear opts