%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: C:\Users\arvr19\Desktop\VR\ResampledMergedSensorVR.xlsx
%    Worksheet: Sheet1
%
% Auto-generated by MATLAB on 06-Aug-2019 13:47:21

%% Setup the Import Options
opts = spreadsheetImportOptions("NumVariables", 5);

% Specify sheet and range
opts.Sheet = "Sheet1";
opts.DataRange = "A2:E2704";

% Specify column names and types
opts.VariableNames = ["DurationVR", "VarName2", "yawVR", "pitchVR", "rollVR"];
opts.SelectedVariableNames = ["DurationVR", "VarName2", "yawVR", "pitchVR", "rollVR"];
opts.VariableTypes = ["string", "string", "string", "string", "string"];
opts = setvaropts(opts, [1, 2, 3, 4, 5], "WhitespaceRule", "preserve");
opts = setvaropts(opts, [1, 2, 3, 4, 5], "EmptyFieldRule", "auto");

% Import the data
ResampledMergedSensorVR = readtable("C:\Users\arvr19\Desktop\VR\ResampledMergedSensorVR.xlsx", opts, "UseExcel", false);

% Read VR Excel data 
duration = xlsread('C:\Users\arvr19\Desktop\VR\ResampledMergedSensorVR.xlsx', 'Sheet1', 'A2:A2704');

yaw = xlsread('C:\Users\arvr19\Desktop\VR\ResampledMergedSensorVR.xlsx', 'Sheet1', 'C2:C2704');
pitch = xlsread('C:\Users\arvr19\Desktop\VR\ResampledMergedSensorVR', 'Sheet1', 'D2:D2704');
roll = xlsread('C:\Users\arvr19\Desktop\VR\ResampledMergedSensorVR.xlsx', 'Sheet1', 'E2:E2704');
 resampleVRduration = resample(duration,3,2);
 resampleVRyaw = resample(yaw,3,2);
 resampleVRpitch = resample(pitch,3,2);
 resampleVRroll = resample(roll,3,2);


%% Clear temporary variables
clear opts